"""Small headless runner used by tools/start_headless.sh

Runs a minimal loop that polls configured connectors for prices and executes
strategy-driven test-ordering logic in PAPER mode.

CANARY MODE: When CANARY_MODE=true, runs in ultra-conservative mode with:
- Slower polling (30s default)
- Verbose narration of every action
- Lower risk limits
- Detailed logging for monitoring
"""
from __future__ import annotations
import os
import time
from typing import List, Optional
import argparse
from datetime import datetime
from pathlib import Path



# RBOTZILLA_PATCH_OANDA_ONLY_SKIP_CONNECTORS_V1
def _rbotzilla_force_oanda_only_env(selected_mode: str) -> None:
    """Hard-force OANDA-only when selected_mode is oanda-only.
    This is a runtime guard to prevent Coinbase/IBKR init + prints."""
    try:
        m = (selected_mode or "").strip().lower()
    except Exception:
        m = ""
    if m == "oanda-only":
        import os
        os.environ["ENABLE_OANDA"] = "true"
        os.environ["ENABLE_COINBASE"] = "false"
        os.environ["ENABLE_IBKR"] = "false"
        # Also kill any paper sim fallback flags if present
        os.environ["PAPER_MODE_SIMULATION"] = "false"

# === RBOTZILLA_GUARD_NO_SIM_FALLBACK (AUTOGENERATED) ===
import os as _os
def _env_bool(k: str, default: str="false") -> bool:
    v = (_os.getenv(k, default) or "").strip().lower()
    return v in ("1","true","yes","y","on")

# Hard policy: OANDA PRACTICE paper only; no fallback simulation; no other brokers.
if _env_bool("ENABLE_COINBASE","false") or _env_bool("ENABLE_IBKR","false"):
    raise RuntimeError("Guard: ENABLE_COINBASE/ENABLE_IBKR must be false (OANDA-only run required).")
if _env_bool("PAPER_MODE_SIMULATION","false"):
    raise RuntimeError("Guard: PAPER_MODE_SIMULATION must be false (no simulation fallback allowed).")

# Hive must have real votes if required.
if _env_bool("ENABLE_HIVE_MIND","true"):
    if _env_bool("REQUIRE_GROK","false") and not (_os.getenv("GROK_API_KEY") or _os.getenv("XAI_API_KEY")):
        raise RuntimeError("Guard: REQUIRE_GROK=true but no GROK/XAI API key found in environment.")
    if _env_bool("REQUIRE_DEEPSEEK","false") and not _os.getenv("DEEPSEEK_API_KEY"):
        raise RuntimeError("Guard: REQUIRE_DEEPSEEK=true but no DEEPSEEK_API_KEY found in environment.")
# === /RBOTZILLA_GUARD_NO_SIM_FALLBACK ===
# ============================================================
# CRITICAL: Load .env file FIRST before any other imports
# This ensures API keys (OPENAI, XAI, DEEPSEEK) are available
# ============================================================
def _load_env_file():
    """Load the canonical .env file properly, handling inline comments.

    Important safety behavior:
    - Never override keys that are already present in the process environment.
    - Within the .env file itself, apply shell-style semantics: LAST value wins.
    - Detect duplicates and warn loudly (duplicates are a common cause of
      silent auth failures when keys are regenerated).
    """
    # Find .env file - look in project root
    script_dir = Path(__file__).resolve().parent
    project_root = script_dir.parent.parent  # Go up from tools/ to MULTI_BROKER_PHOENIX/ to project root
    env_path = project_root / '.env'

    if not env_path.exists():
        print(f"⚠️  No .env file found at {env_path}")
        return

    loaded_count = 0

    # Parse entire file first to detect duplicates and implement last-wins.
    parsed: dict[str, str] = {}
    occurrences: dict[str, list[int]] = {}
    with open(env_path, encoding='utf-8', errors='ignore') as f:
        for i, raw in enumerate(f, start=1):
            line = raw.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue

            # Handle inline comments by splitting on # only if it's after the =
            if '#' in line:
                eq_pos = line.index('=')
                hash_pos = line.find('#', eq_pos)
                if hash_pos > 0:
                    line = line[:hash_pos].strip()

            if '=' not in line:
                continue

            key, value = line.split('=', 1)
            key = key.strip()
            value = value.strip()
            if not key:
                continue

            occurrences.setdefault(key, []).append(i)
            parsed[key] = value  # last occurrence wins

    dupes = {k: v for k, v in occurrences.items() if len(v) > 1}
    if dupes:
        print("🚨 WARNING: Duplicate keys detected in .env (last occurrence will be used):")
        for k in sorted(dupes):
            print(f"   - {k} @ lines {','.join(map(str, dupes[k]))}")
        print("   ✅ To prevent silent failures, fix by removing duplicates (or run tools/env_preflight.py --fix).")

    # Apply parsed keys, but never override process env.
    for key, value in parsed.items():
        if key not in os.environ:
            os.environ[key] = value
            loaded_count += 1

    if loaded_count > 0:
        print(f"✅ Loaded {loaded_count} environment variables from {env_path}")
    
    
    # Verify critical keys
    if os.getenv('OPENAI_API_KEY'):
        print(f"   ✅ OPENAI_API_KEY loaded")
    if os.getenv('XAI_API_KEY'):
        print(f"   ✅ XAI_API_KEY loaded")
    if os.getenv('DEEPSEEK_API_KEY'):
        print(f"   ✅ DEEPSEEK_API_KEY loaded")

# Load env IMMEDIATELY at module import
_load_env_file()

from multi_broker_phoenix.risk.risk_manager import RiskManager
from multi_broker_phoenix.strategies.base import get_strategy
from multi_broker_phoenix.engines.paper_engine import PaperEngine
from multi_broker_phoenix.brokers.coinbase_safe_connector import CoinbaseSafeConnector as CoinbaseConnector

# Use LIVE IBKR connector (connects to TWS/Gateway paper port 4002)
try:
    from multi_broker_phoenix.brokers.ibkr_connector_live import IBKRLiveConnector as IBKRConnector
    IBKR_LIVE_AVAILABLE = True
except ImportError:
    from multi_broker_phoenix.brokers.ibkr_connector import IBKRConnector
    IBKR_LIVE_AVAILABLE = False
    print("⚠️  IBKRLiveConnector not available - falling back to stub (install ib_insync)")

try:
    from multi_broker_phoenix.brokers.oanda_connector import OANDAConnector
except Exception:
    OANDAConnector = None

# Import AI Hive
try:
    import sys
    hive_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), 'hive_real')
    if hive_path not in sys.path:
        sys.path.insert(0, hive_path)
    from api_ai_hive import get_api_ai_vote
    AI_HIVE_AVAILABLE = True
except Exception as exc:
    AI_HIVE_AVAILABLE = False
    print(f'AI Hive not available: {exc}')



def _symbols_from_env() -> List[str]:
    # Coinbase uses hyphen format (BTC-USD), OANDA uses underscore (EUR_USD)
    s = os.getenv('FEED_SYMBOLS', 'BTC-USD,ETH-USD')
    return [x.strip() for x in s.split(',') if x.strip()]


def _is_canary_mode() -> bool:
    """Check if CANARY_MODE is enabled in environment."""
    return os.getenv('CANARY_MODE', 'false').lower() in ('true', '1', 'yes')


def _canary_log(msg: str):
    """Verbose logging for canary mode with timestamp."""
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    print(f"🐤 CANARY [{timestamp}] {msg}")


def _get_poll_interval() -> float:
    """Get polling interval, respecting canary mode override."""
    if _is_canary_mode():
        return float(os.getenv('CANARY_POLL_SECONDS', '30.0'))
    return float(os.getenv('HEADLESS_POLL_SECONDS', '2.0'))


def _get_max_risk_usd() -> float:
    """Get max risk per trade, respecting canary mode override."""
    if _is_canary_mode():
        return float(os.getenv('CANARY_MAX_RISK_USD', '10.0'))
    return float(os.getenv('MAX_RISK_USD_PER_TRADE', '30.0'))


def _choose_mode_interactive(options):
    """Present a simple numeric menu to choose a mode (TTY only). Returns mode key."""
    print('Select headless runner mode:')
    for idx, (k, desc) in enumerate(options.items(), start=1):
        print(f"  {idx}) {k} - {desc}")
    try:
        choice = input('Enter choice number (default 1): ').strip()
        if not choice:
            return list(options.keys())[0]
        i = int(choice) - 1
        return list(options.keys())[i]
    except Exception:
        return list(options.keys())[0]


def _trigger_autonomous_repair(error: Exception):
    """Trigger AI collective to diagnose and repair Hive failure."""
    import traceback
    
    print("\n🤖 INITIATING AUTONOMOUS REPAIR SYSTEM")
    print("   Connected AIs will collectively diagnose and patch the issue...")
    
    # Check if autonomous mode enabled
    if os.getenv('HIVE_AUTONOMOUS_REPAIR', 'false').lower() != 'true':
        print("   ⚠️  Autonomous repair DISABLED (set HIVE_AUTONOMOUS_REPAIR=true)")
        print("   📧 Alert sent - manual intervention required")
        _log_repair_incident(error, "DISABLED", "Autonomous repair not enabled", False)
        return
    
    try:
        # Import repair module
        from hive_real.autonomous_repair import diagnose_and_repair
        
        # Get error details
        error_type = type(error).__name__
        error_msg = str(error)
        error_trace = traceback.format_exc()
        
        print(f"\n🔍 ERROR ANALYSIS:")
        print(f"   Type: {error_type}")
        print(f"   Message: {error_msg}")
        
        # Call AI collective for diagnosis and repair
        result = diagnose_and_repair(
            error_type=error_type,
            error_message=error_msg,
            stack_trace=error_trace
        )
        
        if result['success']:
            print(f"\n✅ REPAIR SUCCESSFUL")
            print(f"   {result['summary']}")
            _log_repair_incident(error, "SUCCESS", result['documentation'], True)
        else:
            print(f"\n❌ REPAIR FAILED")
            print(f"   {result['reason']}")
            _log_repair_incident(error, "FAILED", result['documentation'], False)
            
    except ImportError:
        print("   ⚠️  Autonomous repair module not found")
        print("   📧 Alert sent - manual intervention required")
        _log_repair_incident(error, "MODULE_MISSING", "Repair module not installed", False)
    except Exception as repair_error:
        print(f"   ⚠️  Repair system error: {repair_error}")
        _log_repair_incident(error, "REPAIR_ERROR", str(repair_error), False)


def _log_repair_incident(error: Exception, status: str, details: str, success: bool):
    """Log repair incident to file for human review."""
    import json
    from pathlib import Path
    
    log_dir = Path(os.path.dirname(os.path.dirname(__file__))) / 'hive_real' / 'repair_logs'
    log_dir.mkdir(exist_ok=True)
    
    incident = {
        'timestamp': datetime.now().isoformat(),
        'error_type': type(error).__name__,
        'error_message': str(error),
        'status': status,
        'success': success,
        'details': details
    }
    
    log_file = log_dir / f"repair_log_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(log_file, 'w') as f:
        json.dump(incident, f, indent=2)
    
    print(f"   📝 Incident logged: {log_file}")


def run_headless(mode: Optional[str] = None):
    canary_mode = _is_canary_mode()
    
    if canary_mode:
        _canary_log("🚨 CANARY MODE ACTIVE - Ultra-conservative monitoring enabled")
        _canary_log(f"Polling interval: {_get_poll_interval()}s (slower for safety)")
        _canary_log(f"Max risk per trade: ${_get_max_risk_usd()} (ultra-low)")
    
    print('Starting headless runner (minimal).')
    # Determine mode: CLI arg, env var, or interactive menu
    valid_modes = {
        'auto': 'Auto (prefer platform connectors where appropriate)',
        'multi-asset': 'All brokers: OANDA + IBKR + Coinbase (high-quality AI Hive filtering)',
        'platform-paper': 'Prefer platform paper connectors when available',
        'simulate': 'Simulate only (engine)',
        'oanda-only': 'Use OANDA only (filter by symbol eligibility)',
        'coinbase-only': 'Use Coinbase only',
        'ibkr-only': 'Use IBKR only',
    }
    env_mode = os.getenv('HEADLESS_MODE')
    chosen = mode or env_mode
    if not chosen and os.isatty(0):
        # interactive selection
        chosen = _choose_mode_interactive(valid_modes)
    if not chosen:
        chosen = 'auto'
    if chosen not in valid_modes:
        print(f'Invalid mode {chosen}, falling back to auto')
        chosen = 'auto'
    print(f'Headless mode: {chosen} ({valid_modes.get(chosen)})')
    
    if canary_mode:
        _canary_log(f"Selected mode: {chosen}")

    rm = RiskManager()
    engine = PaperEngine()
    symbols = _symbols_from_env()
    
    if canary_mode:
        _canary_log(f"Initializing connectors for symbols: {', '.join(symbols)}")
    
    # ============================================================
    # BROKER CONFIGURATION (PURGED ALL SIMULATION - API ONLY)
    # ============================================================
    # COINBASE: LIVE TRADING (real money) - starts with nano-lots
    # OANDA: PRACTICE API (real API, paper account)
    # IBKR: PAPER TRADING (real TWS connection, paper port 4002)
    # ============================================================
    
    # Determine Coinbase mode from environment
    coinbase_live = os.getenv('COINBASE_LIVE', 'false').lower() in ('true', '1', 'yes')
    coinbase_enabled = os.getenv('ENABLE_COINBASE', 'false').lower() in ('true', '1', 'yes')
    if chosen == 'coinbase-only':
        coinbase_enabled = True
    if chosen == 'oanda-only':
        coinbase_enabled = False

    coin = None
    if coinbase_enabled:
        try:
            coin = CoinbaseConnector(paper_mode=not coinbase_live, engine=engine)
            mode_label = "🔴 LIVE (REAL MONEY)" if coinbase_live else "🟢 SIMULATION"
            print(f"🧱 Coinbase connector: {mode_label}")
            if coinbase_live:
                print(f"   ⚠️  COINBASE LIVE MODE ACTIVE - Real money trades enabled")
                print(f"   💰 Nano-lot limits: ${coin.min_trade_usd}-${coin.max_trade_usd} per trade")
                print(f"   🛡️  Daily loss limit: ${coin.daily_loss_limit}")
            if canary_mode:
                _canary_log(f"Coinbase connector initialized: {mode_label}")
        except Exception as exc:
            print(f"⚠️  Coinbase connector failed to initialize; continuing: {exc}")
            if canary_mode:
                _canary_log("Coinbase connector failed to initialize")
    else:
        print("🧱 Coinbase connector: skipped (disabled or oanda-only)")

    # IBKR: Real TWS connection to paper trading account (port 4002)
    ibkr_enabled = os.getenv('ENABLE_IBKR', 'false').lower() in ('true', '1', 'yes')
    if chosen == 'ibkr-only':
        ibkr_enabled = True
    if chosen == 'oanda-only':
        ibkr_enabled = False
    ibkr = None
    if ibkr_enabled:
        try:
            ibkr_host = os.getenv('IBKR_HOST', '172.25.80.1')
            ibkr_port = int(os.getenv('IBKR_PORT', '4002'))  # Paper port
            ibkr_client_id = int(os.getenv('IBKR_CLIENT_ID', '1'))
            
            if IBKR_LIVE_AVAILABLE:
                # Use real TWS connection
                ibkr = IBKRConnector(
                    host=ibkr_host,
                    port=ibkr_port,
                    client_id=ibkr_client_id,
                    paper_mode=True,  # Always paper for safety
                    engine=engine
                )
                print(f"🧱 IBKR connector (skipped): 🟡 PAPER TRADING (TWS port {ibkr_port})")
                print(f"   🔗 Connecting to {ibkr_host}:{ibkr_port}")
            else:
                # Fallback to stub connector
                ibkr = IBKRConnector(paper_mode=True, engine=engine)
                print(f"⚠️  IBKR connector: STUB MODE (ib_insync not installed)")
                print(f"   ℹ️  Install ib_insync for real TWS connection")
            
            if canary_mode:
                _canary_log(f"IBKR connector initialized: paper mode (port {ibkr_port})")
        except Exception as exc:
            print(f"⚠️  IBKR connector failed to initialize: {exc}")
            print(f"   ℹ️  Make sure TWS/IB Gateway is running on paper port 4002")
            if canary_mode:
                _canary_log("IBKR connector failed to initialize")
    
    # OANDA: Real API connection to PRACTICE account (api-fxpractice.oanda.com)
    oanda = None
    if OANDAConnector is not None and os.getenv('OANDA_API_TOKEN'):
        # Prefer explicit practice account id when in practice mode
        oanda_account = os.getenv('OANDA_ACCOUNT_ID')
        practice_account = os.getenv('OANDA_PRACTICE_ACCOUNT_ID')
        oanda_mode = (os.getenv('OANDA_MODE') or '').upper()

    # --- Start background bot reporter (writes logs/bot_report.json every 60s)
    def _start_bot_reporter():
        import threading
        import time
        from pathlib import Path
        try:
            from multi_broker_phoenix.monitor.bot_metrics import snapshot_and_reset_window, dump_report_json, append_history
        except Exception:
            snapshot_and_reset_window = None
            dump_report_json = None
            append_history = None

        # optional execution client for open positions
        try:
            from execution.oanda_practice_client import OandaPracticeClient
            cli = OandaPracticeClient(token=os.getenv('OANDA_API_TOKEN'), account_id=os.getenv('OANDA_ACCOUNT_ID'))
        except Exception:
            cli = None

        def _run():
            while True:
                try:
                    report = snapshot_and_reset_window(60) if snapshot_and_reset_window else {'timestamp': time.time()}
                    # enrich report with open trades via execution client
                    try:
                        if cli is not None:
                            ot = cli.list_open_trades()
                            trades = ot.get('trades', [])
                            report['open_positions_count'] = len(trades)
                            exposure = {}
                            for t in trades:
                                sym = t.get('instrument')
                                units = int(float(t.get('currentUnits', 0)))
                                exposure[sym] = exposure.get(sym, 0) + units
                            report['open_exposure_units_by_symbol'] = exposure
                            # attempt P&L if present
                            report['unrealized_pl'] = sum(float(t.get('unrealizedPL', 0.0)) for t in trades)
                    except Exception:
                        pass

                    # write files
                    ts = Path(__file__).resolve().parent.parent / 'logs'
                    json_path = ts / 'bot_report.json'
                    history_path = ts / 'bot_report_history.ndjson'
                    # Prefer using bot_metrics helpers when available
                    if dump_report_json:
                        try:
                            dump_report_json(str(json_path), report)
                        except Exception as e:
                            print(f'REPORT_CARD DUMP ERROR: {e}')
                    else:
                        # fallback: ensure file is written directly
                        try:
                            ts.mkdir(parents=True, exist_ok=True)
                            import json as _json
                            with open(json_path, 'w') as _f:
                                _json.dump(report, _f)
                        except Exception as e:
                            print(f'REPORT_CARD WRITE ERROR: {e}')

                    if append_history:
                        try:
                            append_history(str(history_path), report)
                        except Exception as e:
                            print(f'REPORT_CARD APPEND ERROR: {e}')
                    else:
                        try:
                            ts.mkdir(parents=True, exist_ok=True)
                            import json as _json
                            with open(history_path, 'a') as _h:
                                _h.write(_json.dumps(report) + '\n')
                        except Exception as e:
                            print(f'REPORT_CARD HISTORY ERROR: {e}')

                    print('REPORT_CARD: wrote bot_report.json')
                except Exception as e:
                    print(f'REPORT_CARD ERROR: {e}')
                time.sleep(60)

        t = threading.Thread(target=_run, daemon=True, name='bot_reporter')
        t.start()

    # launch reporter (only if enabled)
    try:
        from global_config import FEATURE_FLAGS as _FF
        reporter_enabled = _FF.get('OANDA_ADVANCED', {}).get('ENABLE_METRICS_REPORTER', True)
    except Exception:
        reporter_enabled = True

    if reporter_enabled:
        try:
            _start_bot_reporter()
        except Exception as e:
            print(f"REPORTER FAILED TO START: {e}")
    else:
        print('REPORTER: disabled by config')

    # start self-tuner loop (evaluates every 10 minutes)
    try:
        from global_config import FEATURE_FLAGS as _FF
        tuner_enabled = _FF.get('OANDA_ADVANCED', {}).get('ENABLE_SELF_TUNER', True)
    except Exception:
        tuner_enabled = True

    if tuner_enabled:
        try:
            from multi_broker_phoenix.monitor.self_tuner import start_loop as _start_self_tuner
            _start_self_tuner()
        except Exception as e:
            print(f"SELF TUNER FAILED TO START: {e}")
    else:
        print('SELF TUNER: disabled by config')

    # Start P&L kill switch monitor (priority #1)
    try:
        from multi_broker_phoenix.monitor.pnl_kill_switch import start_pnl_loop, resolve_pnl_config
        # Respect config toggle before starting
        cfg = resolve_pnl_config().get('pnl_kill_switch', {})
        if cfg.get('enabled', True):
            start_pnl_loop(oanda)
            print(f"✅ PNL_KILL_SWITCH: started (check_interval={cfg.get('check_interval_sec', 5)}s)")
        else:
            print('PNL_KILL_SWITCH: disabled by config')
    except Exception as e:
        print(f"⚠️  Failed to start PNL_KILL_SWITCH: {e}")

    practice_flag = os.getenv('OANDA_PRACTICE', '').lower() in ('true','1','yes')

    # Determine effective account id: prefer practice_account when present and we are in practice mode
    if practice_account and (practice_flag or oanda_mode in ('PAPER','PRACTICE') or os.getenv('TRADING_MODE','PAPER').upper() != 'LIVE'):
        oanda_account = practice_account

    oanda_base_url = os.getenv('OANDA_API_URL', 'https://api-fxpractice.oanda.com')
    
    try:
        oanda = OANDAConnector(
            token=os.getenv('OANDA_API_TOKEN'),
            account_id=oanda_account,
            base_url=oanda_base_url,
            engine=engine,
            practice_mode=True  # Always practice for safety
        )

        # Verify credentials
        cred_check = oanda.verify_credentials()
        if cred_check.get('success'):
            print(f"✅ OANDA connector: 🟡 PRACTICE API (REAL API CONNECTION)")
            print(f"   🔑 Account: {oanda_account}")
            print(f"   🌐 API: {oanda_base_url}")
            print(f"   💱 Currency: {cred_check.get('currency', 'UNKNOWN')}")
            print(f"   ✅ API AUTHENTICATION VERIFIED")
            if canary_mode:
                _canary_log("OANDA connector: API AUTH VERIFIED")
        else:
            print(f"⚠️  OANDA connector: Authentication check failed: {cred_check.get('error')}")
            print(f"   ⚠️  Orders may fail - check API token")
    except Exception as exc:
        print(f"⚠️  OANDA connector failed to initialize: {exc}")
        oanda = None
    else:
        print('⚠️  OANDA connector unavailable or token missing; continuing with other connectors')
        if canary_mode:
            _canary_log("OANDA connector disabled/unavailable")

    # Start the always-on watchdog to monitor OANDA and optional AI seats (Grok/DeepSeek)
    try:
        from multi_broker_phoenix.monitor.watchdog import start_watchdog, resolve_ai_health_urls

        grok_url, deepseek_url = resolve_ai_health_urls()
        if grok_url:
            print(f"✅ WATCHDOG: will monitor Grok/XAI at {grok_url}")
        if deepseek_url:
            print(f"✅ WATCHDOG: will monitor DeepSeek at {deepseek_url}")

        wd_interval = int(os.getenv('WATCHDOG_INTERVAL', '15'))
        if oanda is not None:
            start_watchdog(oanda, grok_url=grok_url, deepseek_url=deepseek_url, interval=wd_interval)
            print(f"✅ WATCHDOG: started (interval={wd_interval}s)")
        else:
            print('⚠️  WATCHDOG: OANDA unavailable; watchdog not started')
    except Exception as e:
        print(f"⚠️  Failed to start WATCHDOG: {e}")

    # START: BrokerLink daemon - maintains broker connectivity and exposes health
    try:
        from multi_broker_phoenix.services.broker_link import BrokerLink
        from pathlib import Path
        state_dir = Path(__file__).resolve().parents[1] / 'ops' / 'state'
        state_dir.mkdir(parents=True, exist_ok=True)

        trading_mode = os.getenv('TRADING_MODE', 'PAPER').upper()
        if oanda is not None:
            broker_link = BrokerLink(oanda, mode='LIVE' if trading_mode == 'LIVE' else 'PAPER')
            broker_link.start()
            print('✅ BROKER_LINK: started')
        else:
            print('⚠️ BROKER_LINK: OANDA unavailable; broker link not started')

        # Engine heartbeat writer
        def _engine_heartbeat_loop():
            hb_file = state_dir / 'engine_heartbeat.json'
            while True:
                try:
                    import time, json
                    with open(hb_file, 'w') as f:
                        json.dump({'ts': time.time()}, f)
                except Exception:
                    pass
                time.sleep(10)

        import threading
        threading.Thread(target=_engine_heartbeat_loop, daemon=True).start()

        # Start periodic self-heal checks in background
        try:
            from multi_broker_phoenix.hive.self_heal import run_self_heal_periodic
            threading.Thread(target=run_self_heal_periodic, args=(oanda, broker_link), daemon=True, name='self-heal').start()
            print('✅ SELF_HEAL: started (periodic checks)')
        except Exception as e:
            print(f"⚠️  SELF_HEAL failed to start: {e}")
    except Exception as e:
        print(f"⚠️  BROKER_LINK failed to start: {e}")
    # END: BrokerLink daemon

    # Run STARTUP RECONCILE before allowing any new trading entries
    try:
        if oanda is not None:
            from multi_broker_phoenix.monitor.protect_and_exit import start_up_reconcile, DEFAULT_RECONCILE_CONFIG
            from multi_broker_phoenix.monitor.watchdog import register_reconnect_callback

            # Ensure trading is frozen until reconcile passes; retry until PASS
            try:
                while True:
                    res = start_up_reconcile(oanda, DEFAULT_RECONCILE_CONFIG)
                    if res.get('passed'):
                        print('✅ STARTUP_RECONCILE: PASS')
                        break
                    else:
                        print('⚠️ STARTUP_RECONCILE: FAIL - retrying in 30s')
                        try:
                            import json
                            print('   details:', json.dumps(res.get('details', {}), indent=2))
                        except Exception:
                            pass
                        time.sleep(30)
            except KeyboardInterrupt:
                print('Startup reconcile interrupted by user')

            # Register reconnect hook so on watchdog restore we re-run startup reconcile
            try:
                register_reconnect_callback(lambda conn: start_up_reconcile(conn, DEFAULT_RECONCILE_CONFIG))

                # Also register a reconnect callback that confirms the HIVE when recovering and we're in LIVE mode
                trading_mode = os.getenv('TRADING_MODE', 'PAPER').upper()
                if trading_mode == 'LIVE':
                    def _confirm_hive_cb(conn):
                        try:
                            import subprocess
                            confirm_script = os.path.join(os.path.dirname(__file__), '..', 'tools', 'confirm_hive.sh')
                            print(f"ℹ️  WATCHDOG RECOVERED: running hive confirmation: {confirm_script}")
                            res = subprocess.run([confirm_script], cwd=os.path.dirname(__file__), check=False)
                            if res.returncode != 0:
                                print('❌ HIVE CONFIRMATION FAILED ON RECONNECT: see tools/hive_confirm.json for details')
                                # If HIVE confirmation fails after a reconnect, keep system fail-closed by exiting process
                                print('Aborting headless process to remain fail-closed')
                                raise RuntimeError('HIVE_CONFIRM_ON_RECONNECT_FAILED')
                            else:
                                print('✅ HIVE CONFIRM on reconnect: real AI seats verified')
                        except Exception as e:
                            print(f"❌ HIVE confirm callback error: {e}")
                            # Re-raise to make failure visible but don't crash the reconnect thread here
                    register_reconnect_callback(_confirm_hive_cb)

            except Exception as e:
                print(f"⚠️  Failed to register reconnect callback: {e}")

            # If we're in LIVE trading mode, confirm the REAL HIVE is responding before allowing trading
            trading_mode = os.getenv('TRADING_MODE', 'PAPER').upper()
            if trading_mode == 'LIVE':
                try:
                    import subprocess
                    confirm_script = os.path.join(os.path.dirname(__file__), '..', 'tools', 'confirm_hive.sh')
                    print(f"ℹ️  LIVE MODE: running hive confirmation: {confirm_script}")
                    res = subprocess.run([confirm_script], cwd=os.path.dirname(__file__), check=False)
                    if res.returncode != 0:
                        raise RuntimeError('Hive confirmation failed; aborting start (see tools/hive_confirm.json or console output)')
                    else:
                        print('✅ HIVE CONFIRM: real AI seats verified')
                except Exception as e:
                    print(f"❌ HIVE CONFIRMATION CHECK FAILED: {e}")
                    print('Aborting headless startup to remain fail-closed')
                    return
        else:
            print('STARTUP_RECONCILE: OANDA unavailable; skipped')
    except Exception as e:
        print(f"⚠️  STARTUP_RECONCILE failed: {e}")

    # Start Protect-or-Exit reconciler (verifies protections and repairs/closes as needed)
    try:
        from global_config import FEATURE_FLAGS as _FF
        protect_enabled = _FF.get('OANDA_ADVANCED', {}).get('ENABLE_PROTECT_RECONCILER', True)
    except Exception:
        protect_enabled = True

    if protect_enabled and oanda is not None:
        try:
            from multi_broker_phoenix.monitor.protect_and_exit import start_reconciler, DEFAULT_RECONCILE_CONFIG
            start_reconciler(oanda, DEFAULT_RECONCILE_CONFIG)
            print(f"✅ PROTECT_RECONCILER: started (interval={DEFAULT_RECONCILE_CONFIG.get('interval_sec')}s)")
        except Exception as e:
            print(f"⚠️  Failed to start PROTECT_RECONCILER: {e}")
    else:
        if not protect_enabled:
            print('PROTECT_RECONCILER: disabled by config')
        else:
            print('PROTECT_RECONCILER: OANDA unavailable; not started')

    # ================================================================
    # "NEVER AGAIN $300 SURPRISE" SAFETY PACK
    # ================================================================
    # Start OCO Reconciler - verifies SL/TP on all open trades and repairs/flattens as needed
    try:
        from multi_broker_phoenix.risk.oco_reconcile import start_oco_reconciler, get_oco_health
        if oanda is not None:
            try:
                from execution.oanda_practice_client import OandaPracticeClient
                oco_client = OandaPracticeClient(
                    token=oanda.token,
                    account_id=oanda.account_id,
                    base_url=oanda.base_url,
                    http_client=oanda.http
                )
                oco_interval = int(os.getenv('OCO_RECONCILE_INTERVAL', '10'))
                start_oco_reconciler(oco_client, {'interval_sec': oco_interval, 'enabled': True})
                print(f"✅ OCO_RECONCILER: started (interval={oco_interval}s)")
            except Exception as e:
                print(f"⚠️  OCO_RECONCILER failed to start: {e}")
        else:
            print('OCO_RECONCILER: OANDA unavailable; not started')
    except Exception as e:
        print(f"⚠️  OCO_RECONCILER module error: {e}")

    # Start Broker Health Monitor with circuit breaker
    try:
        from multi_broker_phoenix.risk.broker_health import (
            start_health_monitor, is_healthy, is_trading_allowed,
            register_reconnect_callback as health_register_cb, enable_trading_after_reconcile
        )
        if oanda is not None:
            health_interval = int(os.getenv('BROKER_HEALTH_INTERVAL', '10'))
            start_health_monitor(oanda, {'check_interval_sec': health_interval, 'enabled': True})
            print(f"✅ BROKER_HEALTH_MONITOR: started (interval={health_interval}s)")
            # Enable trading after startup reconcile passed
            enable_trading_after_reconcile()
        else:
            print('BROKER_HEALTH_MONITOR: OANDA unavailable; not started')
    except Exception as e:
        print(f"⚠️  BROKER_HEALTH_MONITOR module error: {e}")

    # Import Risk Governor for pre-trade validation
    try:
        from multi_broker_phoenix.risk.risk_governor import risk_gate_check, get_config as get_risk_config
        risk_cfg = get_risk_config()
        print(f"✅ RISK_GOVERNOR: loaded (max_risk=${risk_cfg.get('MAX_RISK_USD_PER_TRADE', 25)}, min_rr={risk_cfg.get('MIN_RR', 1.5)})")
    except Exception as e:
        print(f"⚠️  RISK_GOVERNOR module error: {e}")
        risk_gate_check = None
    # ================================================================
    # END SAFETY PACK
    # ================================================================

    # Start breakeven worker (moves SL to breakeven when conditions met)
    try:
        from global_config import FEATURE_FLAGS as _FF
        be_cfg = _FF.get('EXECUTION', {}).get('breakeven', {})
        be_enabled = bool(be_cfg.get('enabled', True))
    except Exception:
        be_cfg = {}
        be_enabled = True

    if be_enabled and oanda is not None:
        try:
            from multi_broker_phoenix.monitor.breakeven_worker import start_breakeven_worker, DEFAULT_BREAKEVEN_CFG
            start_breakeven_worker(oanda, be_cfg or DEFAULT_BREAKEVEN_CFG)
            print(f"✅ BREAKEVEN_WORKER: started (interval={be_cfg.get('interval_sec', DEFAULT_BREAKEVEN_CFG.get('interval_sec'))}s)")
        except Exception as e:
            print(f"⚠️  Failed to start BREAKEVEN_WORKER: {e}")
    else:
        if not be_enabled:
            print('BREAKEVEN_WORKER: disabled by config')
        else:
            print('BREAKEVEN_WORKER: OANDA unavailable; not started')

    # Start exit manager worker (profit lock, trailing, time-stop)
    try:
        exit_cfg = _FF.get('EXIT_MANAGER', {})
        if exit_cfg.get('enabled', True) and oanda is not None:
            # Use the full-featured ExitManager with profit lock + trailing
            from multi_broker_phoenix.risk.exit_manager import start_exit_manager
            exit_mgr = start_exit_manager(oanda, oanda.account_id)
            print('✅ EXIT_MANAGER: started (profit_lock + trailing + time_stop)')
        else:
            print('EXIT_MANAGER: disabled by config or OANDA unavailable')
    except Exception as e:
        print(f"⚠️  Failed to start EXIT_MANAGER: {e}")

    # Start PROTECT LOOP - unified protection cycle (OCO + exit manager + health)
    # This emits PROTECT_LOOP_TICK every cycle to prove runtime wiring
    try:
        from multi_broker_phoenix.risk.protect_loop import start_protect_loop
        if oanda is not None:
            protect_interval = int(os.getenv('PROTECT_LOOP_INTERVAL', '30'))
            start_protect_loop(oanda, interval_sec=protect_interval, account_id=oanda.account_id)
            print(f"✅ PROTECT_LOOP: started (interval={protect_interval}s, emits PROTECT_LOOP_TICK)")
        else:
            print('PROTECT_LOOP: OANDA unavailable; not started')
    except Exception as e:
        print(f"⚠️  Failed to start PROTECT_LOOP: {e}")

    # Load ALL strategies from ENABLED_STRATEGIES (comma-separated list)
    enabled_strategy_names = os.getenv('ENABLED_STRATEGIES', 'fabio_aaa_full,holy_grail,ema_scalper,institutional_sd').split(',')
    strategies = {}
    for strat_name in enabled_strategy_names:
        strat_name = strat_name.strip()
        if strat_name:
            try:
                strategies[strat_name] = get_strategy(strat_name)
                print(f"✅ Strategy loaded: {strat_name}")
            except Exception as e:
                print(f"⚠️  Strategy {strat_name} failed to load: {e}")
    
    if not strategies:
        # Fallback to default if none loaded
        default_strat = os.getenv('DEFAULT_STRATEGY', 'holy_grail')
        strategies[default_strat] = get_strategy(default_strat)
        print(f"⚠️  Using fallback strategy: {default_strat}")
    
    if canary_mode:
        _canary_log(f"Strategies loaded: {', '.join(strategies.keys())}")
    
    prices = {s: [] for s in symbols}
    
    # PRE-LOAD HISTORICAL DATA for each symbol (so strategies have data immediately)
    print("📊 Pre-loading historical data for instant signal generation...")
    for sym in symbols:
        try:
            if '-' in sym and coin:  # Coinbase symbol
                historical = coin.get_historical_data(sym, periods=100, granularity=300)  # 5-min candles
                if historical:
                    prices[sym] = historical
                    print(f"   ✅ {sym}: {len(historical)} candles loaded (${min(historical):.0f} - ${max(historical):.0f})")
            elif '_' in sym and oanda:  # OANDA symbol
                # Try OANDA historical
                try:
                    hist_data = oanda.get_historical_data(sym, count=100)
                    if hist_data:
                        hist_prices = [float(p.get('mid', {}).get('c', 0)) for p in hist_data if float(p.get('mid', {}).get('c', 0)) > 0]
                        if hist_prices:
                            prices[sym] = hist_prices
                            print(f"   ✅ {sym}: {len(hist_prices)} prices loaded from OANDA")
                except Exception as e:
                    print(f"   ⚠️  {sym}: OANDA historical failed: {e}")
        except Exception as e:
            print(f"   ⚠️  {sym}: Failed to load historical data: {e}")
    
    print(f"📈 Historical data loaded. Ready for immediate signal detection!")

    try:
        loop_count = 0
        # Cycle telemetry counters to avoid silent failures (signals, blocks, orders, no-price)
        cycle_counters = {
            'signals': 0,
            'blocked_ai': 0,
            'blocked_risk': 0,
            'blocked_watchdog': 0,
            'orders_placed': 0,
            'no_price': 0
        }
        if canary_mode:
            _canary_log("🚀 Starting main loop - monitoring all activity")
        
        while True:
            loop_count += 1
            if canary_mode and loop_count % 10 == 1:  # Every 10th iteration
                _canary_log(f"Loop #{loop_count} - Health check OK")
            
            for sym in symbols:
                # poll each connector for a price
                price = None
                # Route based on mode or symbol pattern
                if chosen == 'coinbase-only' or (chosen in ('auto', 'multi-asset') and '-' in sym):
                    if coin is not None:
                        price = coin.fetch_live_price(sym)
                    else:
                        price = None
                    if canary_mode and price:
                        _canary_log(f"📊 {sym} price: ${price:.2f} (Coinbase)")
                elif chosen == 'ibkr-only':
                    if ibkr is not None:
                        price = ibkr.get_last_price(sym)
                    else:
                        price = None
                    if canary_mode and price:
                        _canary_log(f"📊 {sym} price: ${price:.2f} (IBKR)")
                elif oanda and ('_' in sym or chosen in ('oanda-only', 'multi-asset')):
                    price = oanda.get_last_price(sym)
                    if canary_mode and price:
                        _canary_log(f"📊 {sym} price: ${price:.2f} (OANDA)")
                else:
                    # fallback: try coin then ibkr
                    price = (coin.fetch_live_price(sym) if coin is not None else None) or (ibkr.get_last_price(sym) if ibkr is not None else None)
                    if canary_mode and price:
                        _canary_log(f"📊 {sym} price: ${price:.2f} (fallback)")
                
                if price is None:
                    cycle_counters['no_price'] += 1
                    if canary_mode:
                        _canary_log(f"⚠️  {sym} price unavailable - skipping")
                    continue
                prices[sym].append(price)
                if len(prices[sym]) > 200:
                    prices[sym] = prices[sym][-200:]
                
                # Log price history depth
                if loop_count <= 25 and loop_count % 5 == 0:
                    print(f"   📈 {sym}: {len(prices[sym])} prices collected (need 20+ for signals)")
                
                # Try ALL strategies for this symbol
                for strat_name, strategy in strategies.items():
                    cand = strategy.generate_candidate({'symbol': sym, 'platform':'HEADLESS', 'prices': prices[sym]})
                    if not cand:
                        if canary_mode and loop_count % 10 == 1:
                            _canary_log(f"✋ {sym}/{strat_name} - No signal")
                        continue
                    
                    # Record signal
                    cycle_counters['signals'] += 1
                    if canary_mode:
                        _canary_log(f"🎯 {sym} SIGNAL ({strat_name}): {cand.side} @ ${price:.2f}")
                
                    # Decide target platform based on symbol if strategy did not set one
                    platform_guess = 'OANDA' if '_' in sym else 'COINBASE' if '-' in sym else 'IBKR'
                    try:
                        if not getattr(cand, 'platform', None):
                            cand.platform = platform_guess
                    except Exception:
                        pass
                    from multi_broker_phoenix.risk.trade_risk_gate import can_open_trade
                    dec = can_open_trade(cand, account_equity=rm.state.equity_now or 100000.0, rm=rm)
                    if not dec.allowed:
                        cycle_counters['blocked_risk'] += 1
                        print(f"trade blocked: {dec.reason}")
                        if canary_mode:
                            _canary_log(f"🚫 Trade BLOCKED: {dec.reason}")
                        continue
                    
                    # AI Hive consensus check
                    if AI_HIVE_AVAILABLE and os.getenv('ENABLE_AI_HIVE', 'false').lower() == 'true':
                        # Check for emergency bypass (manual override)
                        if os.getenv('HIVE_EMERGENCY_BYPASS', 'false').lower() == 'true':
                            print("⚠️  EMERGENCY BYPASS ACTIVE - Hive disabled by manual override")
                            if canary_mode:
                                _canary_log("⚠️  EMERGENCY BYPASS - Manual override active")
                        else:
                            try:
                                # Get recent prices for Hive analysis
                                recent_prices = []
                                try:
                                    if '_' in sym:  # OANDA
                                        if oanda:
                                            prices_data = oanda.get_historical_data(sym, count=30)
                                            recent_prices = [float(p.get('mid', {}).get('c', 0)) for p in prices_data]
                                    elif '-' in sym:  # Coinbase
                                        prices_data = coin.get_historical_data(sym, periods=30)
                                        recent_prices = [float(p) for p in prices_data]
                                except Exception:
                                    recent_prices = [cand.entry_price] * 10  # Fallback to current price
                                
                                market_data = {'prices': recent_prices or [cand.entry_price]}
                                hive_result = get_api_ai_vote(sym, cand.side.upper(), cand.entry_price, market_data)
                                
                                if canary_mode:
                                    _canary_log(f"🤖 AI Hive: {hive_result['vote']} (consensus: {hive_result.get('consensus', 0):.1%})")
                                
                                # Block if not approved
                                if hive_result['vote'] not in ['approve', 'execute']:
                                    cycle_counters['blocked_ai'] += 1
                                    print(f"AI Hive blocked trade: {hive_result['reasoning']}")
                                    if canary_mode:
                                        _canary_log(f"🚫 AI Hive BLOCKED: {hive_result['reasoning']}")
                                    continue
                                    
                            except Exception as hive_exc:
                                # CRITICAL FAILURE - Trigger self-healing
                                print(f"🚫 AI HIVE CRITICAL FAILURE - BLOCKING ALL NEW TRADES")
                                print(f"   Error: {hive_exc}")
                                if canary_mode:
                                    _canary_log(f"🚨 CRITICAL: AI Hive failure - {hive_exc}")
                                
                                # Trigger autonomous diagnosis and repair
                                _trigger_autonomous_repair(hive_exc)
                                continue  # HALT - no trade execution on Hive failure
                    
                    sizing = rm.size_for_trade(cand, rm.state.equity_now or 100000.0, fee_pct=coin.fee_pct, slippage_pct=coin.slippage_pct)
                    if not sizing.get('allowed'):
                        print('sizing rejected:', sizing.get('reason'))
                        if canary_mode:
                            _canary_log(f"🚫 Sizing REJECTED: {sizing.get('reason')}")
                        continue
                    
                    if canary_mode:
                        _canary_log(f"✅ Risk checks PASSED - Size: {sizing['size']} units")
                    
                    # ================================================================
                    # RISK GOVERNOR: Hard veto if risk exceeds budget (NEVER AGAIN $300 SURPRISE)
                    # ================================================================
                    try:
                        if risk_gate_check is not None:
                            units = int(sizing['size']) if isinstance(sizing['size'], (int, float)) else int(float(sizing['size']))
                            rg_result = risk_gate_check(cand, units)
                            if not rg_result['allowed']:
                                cycle_counters['blocked_risk'] += 1
                                print(f"🚫 RISK_GOVERNOR VETO: {rg_result['reason']}")
                                metrics = rg_result.get('metrics', {})
                                if metrics:
                                    print(f"   💰 Risk to SL: ${metrics.get('risk_to_sl_usd', 0):.2f}")
                                    print(f"   📊 RR Ratio: {metrics.get('rr_ratio', 0):.2f}")
                                    print(f"   📈 Pip Value: ${metrics.get('pip_value_usd', 0):.2f}/pip")
                                if rg_result.get('suggested_units'):
                                    print(f"   💡 Suggested Units: {rg_result['suggested_units']}")
                                if canary_mode:
                                    _canary_log(f"🚫 RISK_GOVERNOR VETO: {rg_result['reason']}")
                                continue
                            else:
                                # Log approved trade metrics
                                metrics = rg_result.get('metrics', {})
                                if canary_mode:
                                    _canary_log(f"✅ RISK_GOVERNOR PASS: risk=${metrics.get('risk_to_sl_usd', 0):.2f}, RR={metrics.get('rr_ratio', 0):.2f}")
                    except Exception as e:
                        print(f"⚠️ RISK_GOVERNOR check failed: {e}; proceeding with caution")
                    # ================================================================
                    # END RISK GOVERNOR
                    # ================================================================
                    
                    # WATCHDOG: If watchdog has frozen new trades, skip placing any new order
                    try:
                        from multi_broker_phoenix.monitor.watchdog import trading_allowed as _watchdog_trading_allowed
                        if not _watchdog_trading_allowed():
                            cycle_counters['blocked_watchdog'] += 1
                            print("🚨 WATCHDOG: new trades are currently frozen - skipping order placement")
                            if canary_mode:
                                _canary_log("🚫 WATCHDOG: new trades frozen - skipping")
                            continue
                    except Exception:
                        # If watchdog import fails for any reason, allow normal flow but warn
                        print("⚠️ WATCHDOG: check unavailable (import failed); proceeding")
                    # Choose connector based on symbol/platform and prefer platform paper when available
                    order = None
                    try:
                        # Prefer explicit platform in candidate
                        platform = getattr(cand, 'platform', None) or ( 'OANDA' if '_' in sym else 'COINBASE' if '-' in sym else 'IBKR' )
                        
                        if canary_mode:
                            _canary_log(f"📝 Preparing order: {cand.side} {sym} via {platform}")
                        
                        # ============================================================
                        # ORDER ROUTING: REAL API CONNECTIONS (NO SIMULATION)
                        # ============================================================
                        # OANDA: place_paper_order() -> Real Practice API
                        # IBKR: place_paper_order() -> Real TWS Paper Port 4002
                        # COINBASE: place_live_order() if COINBASE_LIVE=true (REAL MONEY)
                        #           place_paper_order() otherwise (simulation)
                        # ============================================================
                        
                        # Mode-driven routing
                        if chosen == 'simulate':
                            order = engine.place_order(cand, sizing['size'], execution_type='SIMULATED')
                            if canary_mode:
                                _canary_log(f"✅ SIMULATED order placed: {order}")
                        elif chosen == 'oanda-only':
                            if oanda is None:
                                raise RuntimeError('OANDA connector not initialized')
                            units = int(sizing['size']) if isinstance(sizing['size'], (int, float)) else int(float(sizing['size']))
                            # Check broker connectivity via BrokerLink (if present)
                            try:
                                if 'broker_link' in globals() and broker_link is not None and not broker_link.is_connected():
                                    cycle_counters['blocked_broker'] += 1
                                    print("🚨 BROKER_DISCONNECTED: trading paused - skipping order placement")
                                    try:
                                        from multi_broker_phoenix.monitor.pnl_kill_switch import _log_event
                                        _log_event('ENGINE_TRADING_PAUSED', {'reason': 'broker_disconnected'})
                                    except Exception:
                                        pass
                                    order = None
                                else:
                                    order = oanda.place_paper_order(cand, units=units)
                                    print(f"🟡 OANDA PRACTICE ORDER: {sym} {cand.side} x{units}")
                                    if canary_mode:
                                        _canary_log(f"✅ OANDA PRACTICE order via API: {order}")
                            except Exception as e:
                                print(f"❌ OANDA order attempt failed: {e}")
                                order = None
                        elif chosen == 'coinbase-only':
                            if coin is None:
                                raise RuntimeError('Coinbase connector not initialized')
                            if coinbase_live:
                                # REAL MONEY ORDER
                                order = coin.place_live_order(cand, sizing['size'], confirm_real_money=True)
                                print(f"🔴 COINBASE LIVE ORDER (REAL $$$): {sym} {cand.side}")
                            else:
                                order = coin.place_paper_order(cand, sizing['size'])
                            if canary_mode:
                                _canary_log(f"✅ COINBASE order placed: {order}")
                        elif chosen == 'ibkr-only':
                            if ibkr is None:
                                raise RuntimeError('IBKR connector not initialized')
                            order = ibkr.place_paper_order(cand, sizing['size'])
                            print(f"🟡 IBKR PAPER ORDER (TWS): {sym} {cand.side}")
                            if canary_mode:
                                _canary_log(f"✅ IBKR PAPER order via TWS: {order}")
                        else:
                            # 'auto' or 'multi-asset' or 'platform-paper' behavior
                            platform = getattr(cand, 'platform', None) or ( 'OANDA' if '_' in sym else 'COINBASE' if '-' in sym else 'IBKR' )
                            
                            if platform == 'OANDA' and oanda is not None:
                                # Run entry gate checks before placing any order
                                try:
                                    from execution.entry_gate import EntryGate
                                    try:
                                        from execution.scorecard import score_signal
                                    except Exception:
                                        # tolerant: scorecard optional
                                        score_signal = None
                                    market_data = {'symbol': sym, 'bid': None, 'ask': None, 'prices': prices.get(sym, [])}
                                    try:
                                        p = oanda.get_prices([sym]).get('prices', [])
                                        if p:
                                            market_data['bid'] = float(p[0].get('closeoutBid') or p[0].get('bid') or 0.0)
                                            market_data['ask'] = float(p[0].get('closeoutAsk') or p[0].get('ask') or 0.0)
                                            market_data['spread_pips'] = abs(market_data['ask'] - market_data['bid']) / (0.01 if 'JPY' in sym else 0.0001)
                                    except Exception:
                                        pass

                                    gate = EntryGate.evaluate(cand, market_data, rm)
                                    if not gate.get('allow'):
                                        print(f"ENTRY_GATE: blocked ({','.join(gate.get('reasons', []))}) - skipping order placement")
                                        order = None
                                    else:
                                        features = {
                                            'htf_alignment': 1.0,
                                            'structure': 1.0,
                                            'momentum': 1.0,
                                            'volatility_sanity': 1.0 if gate['metrics'].get('atr', 0.0) > 0 else 0.0,
                                            'spread_sanity': 1.0 if gate['metrics'].get('spread_pips', 0.0) <= (_FF.get('ENTRY_GATE',{}).get('max_spread_pips_by_pair',{}).get('MAJOR',1.6)) else 0.0,
                                            'risk_feasibility': 1.0 if sizing.get('allowed') else 0.0
                                        }
                                        if score_signal:
                                            sc = score_signal(features)
                                            if not sc.get('passed'):
                                                print(f"SCORECARD: blocked (score={sc.get('score'):.1f}) - skipping order")
                                                order = None
                                            else:
                                                units = int(sizing['size']) if isinstance(sizing['size'], (int, float)) else int(float(sizing['size']))
                                                # Broker connectivity guard
                                                try:
                                                    if 'broker_link' in globals() and broker_link is not None and not broker_link.is_connected():
                                                        cycle_counters['blocked_broker'] += 1
                                                        print("🚨 BROKER_DISCONNECTED: trading paused - skipping order placement")
                                                        try:
                                                            from multi_broker_phoenix.monitor.pnl_kill_switch import _log_event
                                                            _log_event('ENGINE_TRADING_PAUSED', {'reason': 'broker_disconnected'})
                                                        except Exception:
                                                            pass
                                                        order = None
                                                    else:
                                                        order = oanda.place_paper_order(cand, units=units)
                                                        print(f"🟡 OANDA PRACTICE: {sym} {cand.side} x{units}")
                                                except Exception as e:
                                                    print(f"❌ OANDA order attempt failed: {e}")
                                                    order = None
                                        else:
                                            units = int(sizing['size']) if isinstance(sizing['size'], (int, float)) else int(float(sizing['size']))
                                            try:
                                                if 'broker_link' in globals() and broker_link is not None and not broker_link.is_connected():
                                                    cycle_counters['blocked_broker'] += 1
                                                    print("🚨 BROKER_DISCONNECTED: trading paused - skipping order placement")
                                                    try:
                                                        from multi_broker_phoenix.monitor.pnl_kill_switch import _log_event
                                                        _log_event('ENGINE_TRADING_PAUSED', {'reason': 'broker_disconnected'})
                                                    except Exception:
                                                        pass
                                                    order = None
                                                else:
                                                    order = oanda.place_paper_order(cand, units=units)
                                                    print(f"🟡 OANDA PRACTICE: {sym} {cand.side} x{units}")
                                            except Exception as e:
                                                print(f"❌ OANDA order attempt failed: {e}")
                                                order = None
                                except Exception as exc:
                                    print(f"⚠️ ENTRY_GATE/SCORECARD check failed, proceeding cautiously: {exc}")
                                    units = int(sizing['size']) if isinstance(sizing['size'], (int, float)) else int(float(sizing['size']))
                                    try:
                                        if 'broker_link' in globals() and broker_link is not None and not broker_link.is_connected():
                                            cycle_counters['blocked_broker'] += 1
                                            print("🚨 BROKER_DISCONNECTED: trading paused - skipping order placement")
                                            try:
                                                from multi_broker_phoenix.monitor.pnl_kill_switch import _log_event
                                                _log_event('ENGINE_TRADING_PAUSED', {'reason': 'broker_disconnected'})
                                            except Exception:
                                                pass
                                            order = None
                                        else:
                                            order = oanda.place_paper_order(cand, units=units)
                                    except Exception as e:
                                        print(f"❌ OANDA order attempt failed (fallback guard): {e}")
                                        order = None
                            elif platform == 'IBKR' and ibkr is not None:
                                order = ibkr.place_paper_order(cand, sizing['size'])
                                print(f"🟡 IBKR PAPER: {sym} {cand.side}")
                            elif platform == 'COINBASE' and coin is not None:
                                if coinbase_live:
                                    # REAL MONEY ORDER
                                    order = coin.place_live_order(cand, sizing['size'], confirm_real_money=True)
                                    print(f"🔴 COINBASE LIVE (REAL $$$): {sym} {cand.side}")
                                else:
                                    order = coin.place_paper_order(cand, sizing['size'])
                                    print(f"🟢 COINBASE SIM: {sym} {cand.side}")
                            else:
                                # Final fallback to engine
                                order = engine.place_order(cand, sizing['size'])
                                print(f"⚠️  FALLBACK to engine: {sym} {cand.side}")
                            
                            if canary_mode:
                                _canary_log(f"✅ Order placed via {platform}: {order}")
                    except Exception as exc:
                        # Last-resort: simulated engine (but warn loudly)
                        order = engine.place_order(cand, sizing['size'])
                        print(f'⚠️  PLATFORM ORDER FAILED, fell back to engine: {exc}')
                        if canary_mode:
                            _canary_log(f"⚠️  Platform order FAILED, engine fallback: {exc}")
                    print('placed order:', order)
                try:
                    cycle_counters['orders_placed'] += 1
                except Exception:
                    pass
            
            poll_interval = _get_poll_interval()
            # Cycle summary telemetry
            if canary_mode:
                _canary_log(f"📊 Cycle summary: signals={cycle_counters['signals']}, blocked_ai={cycle_counters['blocked_ai']}, blocked_risk={cycle_counters['blocked_risk']}, blocked_watchdog={cycle_counters['blocked_watchdog']}, orders={cycle_counters['orders_placed']}, no_price={cycle_counters['no_price']}")
            # Reset counters for next cycle
            cycle_counters = {
                'signals': 0,
                'blocked_ai': 0,
                'blocked_risk': 0,
                'blocked_watchdog': 0,
                'orders_placed': 0,
                'no_price': 0
            }
            if canary_mode and loop_count % 10 == 0:
                _canary_log(f"😴 Sleeping {poll_interval}s until next check...")
            time.sleep(poll_interval)
    except KeyboardInterrupt:
        print('Headless runner stopped by user')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Headless runner (minimal loop)')
    parser.add_argument('--mode', help='Runner mode (overrides HEADLESS_MODE env var)', choices=['auto','multi-asset','platform-paper','simulate','oanda-only','coinbase-only','ibkr-only'])
    args = parser.parse_args()
    run_headless(mode=args.mode)
    _rbotzilla_force_oanda_only_env(str(args.mode or ''))

