#!/usr/bin/env bash
# RBOTzilla Secrets Bootstrap - ONE COMMAND TO RESTORE KEYS
# Migrates keys from running engine PID or .env WITHOUT printing secrets
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

SECRETS_FILE="${REPO_ROOT}/ops/secrets.env"
BACKUP_DIR="${REPO_ROOT}/ops/backups"
TIMESTAMP=$(date -u +%Y%m%dT%H%M%SZ)

echo "========================================="
echo " RBOTzilla Secrets Bootstrap"
echo "========================================="
echo ""

# Create backup dir
mkdir -p "$BACKUP_DIR"

# Backup existing secrets file if present
if [[ -f "$SECRETS_FILE" ]]; then
    BACKUP_PATH="${BACKUP_DIR}/secrets.env.backup.${TIMESTAMP}"
    cp "$SECRETS_FILE" "$BACKUP_PATH"
    echo "✅ Backed up existing secrets to: $BACKUP_PATH"
    echo ""
fi

# Whitelist of keys to extract (NEVER print these values)
WHITELISTED_KEYS=(
    "OANDA_API_TOKEN"
    "OANDA_ACCOUNT_ID"
    "OANDA_API_URL"
    "XAI_API_KEY"
    "DEEPSEEK_API_KEY"
    "OPENAI_API_KEY"
    "OLLAMA_URL"
    "OLLAMA_MODEL"
)

# Helper: extract key from /proc/<PID>/environ (NO VALUE LEAK)
_extract_from_proc() {
    local pid="$1"
    local key="$2"
    if [[ ! -f "/proc/$pid/environ" ]]; then
        return 1
    fi
    # /proc/PID/environ is null-delimited, grep for KEY=VALUE, extract value
    tr '\0' '\n' < "/proc/$pid/environ" 2>/dev/null | grep "^${key}=" | cut -d= -f2- || true
}

# Helper: extract key from .env file (NO VALUE LEAK)
_extract_from_file() {
    local file="$1"
    local key="$2"
    if [[ ! -f "$file" ]]; then
        return 1
    fi
    grep "^${key}=" "$file" 2>/dev/null | tail -1 | cut -d= -f2- || true
}

# Strategy 1: Try running engine PID
ENGINE_PID=""
if [[ -f "${REPO_ROOT}/ops/state/engine.pid" ]]; then
    ENGINE_PID=$(cat "${REPO_ROOT}/ops/state/engine.pid" 2>/dev/null || true)
fi

# Fallback: grep ps for run_headless
if [[ -z "$ENGINE_PID" ]]; then
    ENGINE_PID=$(ps aux | grep -E "run_headless|engine_headless" | grep -v grep | awk '{print $2}' | head -1 || true)
fi

EXTRACTED_KEYS=()
SOURCE_METHOD=""

if [[ -n "$ENGINE_PID" ]] && kill -0 "$ENGINE_PID" 2>/dev/null; then
    echo "🔍 Found running engine PID: $ENGINE_PID"
    echo "   Extracting keys from /proc/$ENGINE_PID/environ..."
    echo ""
    
    # Extract whitelisted keys from running process
    for key in "${WHITELISTED_KEYS[@]}"; do
        val=$(_extract_from_proc "$ENGINE_PID" "$key")
        if [[ -n "$val" ]]; then
            EXTRACTED_KEYS+=("${key}=${val}")
        fi
    done
    SOURCE_METHOD="running_engine_pid_${ENGINE_PID}"

elif [[ -f "${REPO_ROOT}/.env" ]]; then
    echo "⚠️  No running engine found."
    echo "🔍 Trying .env file..."
    echo ""
    
    # Extract whitelisted keys from .env
    for key in "${WHITELISTED_KEYS[@]}"; do
        val=$(_extract_from_file "${REPO_ROOT}/.env" "$key")
        if [[ -n "$val" ]]; then
            EXTRACTED_KEYS+=("${key}=${val}")
        fi
    done
    SOURCE_METHOD=".env_file"
else
    echo "❌ No running engine and no .env file found."
    echo "   Creating empty template with placeholders..."
    echo ""
    SOURCE_METHOD="empty_template"
fi

# Write secrets file (chmod 600, NO ECHOING VALUES)
if [[ ${#EXTRACTED_KEYS[@]} -gt 0 ]]; then
    {
        echo "# RBOTzilla Secrets (auto-generated by bootstrap_secrets.sh)"
        echo "# Source: $SOURCE_METHOD"
        echo "# Timestamp: $TIMESTAMP"
        echo ""
        for line in "${EXTRACTED_KEYS[@]}"; do
            echo "$line"
        done
    } > "$SECRETS_FILE"
    
    chmod 600 "$SECRETS_FILE"
    
    echo "✅ Created $SECRETS_FILE"
    echo "   Source: $SOURCE_METHOD"
    echo "   Keys extracted: ${#EXTRACTED_KEYS[@]}"
    echo ""
    
    # Show presence-only summary (NO VALUES)
    echo "PRESENCE CHECK (no values shown):"
    for key in "${WHITELISTED_KEYS[@]}"; do
        if grep -q "^${key}=" "$SECRETS_FILE" 2>/dev/null; then
            echo "  $key = [SET]"
        else
            echo "  $key = [EMPTY]"
        fi
    done
else
    # Create empty template
    {
        echo "# RBOTzilla Secrets (empty template - FILL IN YOUR KEYS)"
        echo "# Timestamp: $TIMESTAMP"
        echo ""
        echo "OANDA_API_TOKEN="
        echo "OANDA_ACCOUNT_ID="
        echo "OANDA_API_URL=https://api-fxpractice.oanda.com"
        echo ""
        echo "XAI_API_KEY="
        echo "DEEPSEEK_API_KEY="
        echo "OPENAI_API_KEY="
        echo ""
        echo "OLLAMA_URL=http://127.0.0.1:11434"
        echo "OLLAMA_MODEL=llama3.1:8b"
    } > "$SECRETS_FILE"
    
    chmod 600 "$SECRETS_FILE"
    
    echo "⚠️  Created empty template: $SECRETS_FILE"
    echo "   YOU MUST MANUALLY FILL IN YOUR KEYS."
fi

echo ""
echo "========================================="
echo " Running env_doctor to verify..."
echo "========================================="
echo ""

# Run env_doctor to verify
bash "${REPO_ROOT}/tools/env_doctor.sh" || true

echo ""
echo "========================================="
echo " Bootstrap complete!"
echo "========================================="
